name: Build Tweaks for arm64e

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: /usr/local/theos
      TARGET: iphone:clang:latest:18.0
      ARCHS: arm64e

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install ldid dpkg wget

    - name: Install Theos
      run: |
        git clone --depth=1 https://github.com/theos/theos.git $THEOS

    - name: Build v1.1 (Logos)
      working-directory: ./SideloadBypass1.1
      run: |
        make clean package
        mkdir -p ../artifacts
        cp .theos/obj/debug/SideloadBypass1.dylib ../artifacts/

    - name: Build v2.1 (CaptainHook)
      working-directory: ./SideloadBypass2.1
      run: |
        make clean package
        cp .theos/obj/debug/SideloadBypass2.dylib ../artifacts/

    - name: Archive dylibs
      run: |
        cd artifacts
        zip -r SideloadBypass_artifacts.zip SideloadBypass1.dylib SideloadBypass2.dylib

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SideloadBypass-dylibs
        path: artifacts/SideloadBypass_artifacts.zip
